apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJSR0Z1YTI4eU1EQXdPbWRvY0Y5SE4yeDRaV2xWVlVkclJGWkRVa0ZJVjJKcU4xcDBjems1TVhCUFNqSXdPWE00ZDBFIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson
